/* tslint:disable */
/* eslint-disable */
/**
 * Devmarks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookmarkRequest
 */
export interface CreateBookmarkRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    color?: string;
}

export function CreateBookmarkRequestFromJSON(json: any): CreateBookmarkRequest {
    return CreateBookmarkRequestFromJSONTyped(json, false);
}

export function CreateBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookmarkRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'color': !exists(json, 'color') ? undefined : json['color'],
    };
}

export function CreateBookmarkRequestToJSON(value?: CreateBookmarkRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
        'color': value.color,
    };
}


