/* tslint:disable */
/* eslint-disable */
/**
 * Devmarks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBookmarkRequest
 */
export interface UpdateBookmarkRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateBookmarkRequest
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    color?: string;
}

export function UpdateBookmarkRequestFromJSON(json: any): UpdateBookmarkRequest {
    return UpdateBookmarkRequestFromJSONTyped(json, false);
}

export function UpdateBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookmarkRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'color': !exists(json, 'color') ? undefined : json['color'],
    };
}

export function UpdateBookmarkRequestToJSON(value?: UpdateBookmarkRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'color': value.color,
    };
}


